routes/web.php
<?php

use App\Http\Controllers\PatientController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [UserController::class, 'index']);
Route::resources(['user' => UserController::class]);
Route::get('seed/data', [UserController::class, 'seedData'])->name('user.seeder');

Route::resources(['patient' => PatientController::class]);
Route::get('seed-data', [PatientController::class, 'seedData'])->name('patient.seeder');

app/Models/Patient.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Patient extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'email', 'phone', 'address'];

}

app/Http/Controllers/PatientController.php
<?php

namespace App\Http\Controllers;

use App\Models\Patient;
use Faker\Generator as Faker;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class PatientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $search = \request('search', '');


        $patients = Patient::select(
            'id',
            DB::raw("AES_DECRYPT(FROM_BASE64(`name`), '" . env('APP_KEY') . "') as name"),
            DB::raw("AES_DECRYPT(FROM_BASE64(`email`), '" . env('APP_KEY') . "') as email"),
            DB::raw("AES_DECRYPT(FROM_BASE64(`phone`), '" . env('APP_KEY') . "') as phone"),
            DB::raw("AES_DECRYPT(FROM_BASE64(`address`), '" . env('APP_KEY') . "') as address")
        )->where(function ($q) use ($search) {
            if ($search)
            {
                $q->where(DB::raw("AES_DECRYPT(FROM_BASE64(`name`), '" . env('APP_KEY') . "')"), 'like', "%{$search}%");
                $q->orWhere(DB::raw("AES_DECRYPT(FROM_BASE64(`email`), '" . env('APP_KEY') . "')"), 'like', "%{$search}%");
                $q->orWhere(DB::raw("AES_DECRYPT(FROM_BASE64(`phone`), '" . env('APP_KEY') . "')"), 'like', "%{$search}%");
                $q->orWhere(DB::raw("AES_DECRYPT(FROM_BASE64(`address`), '" . env('APP_KEY') . "')"), 'like', "%{$search}%");
            }
        })->paginate();

        return view('patient.index')->with('patients', $patients);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('patient._from');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'    => 'required',
            'email'   => 'required|email|unique:users',
            'phone'   => 'required',
            'address' => 'required',
        ]);


        $input['name']    = DB::raw("TO_BASE64(AES_ENCRYPT('" . str_replace("'", "", $request->name) . "', '" . env('APP_KEY') . "'))");
        $input['email']   = DB::raw("TO_BASE64(AES_ENCRYPT('" . str_replace("'", "", $request->email) . "', '" . env('APP_KEY') . "'))");
        $input['phone']   = DB::raw("TO_BASE64(AES_ENCRYPT('" . str_replace("'", "", $request->phone) . "', '" . env('APP_KEY') . "'))");
        $input['address'] = DB::raw("TO_BASE64(AES_ENCRYPT('" . str_replace("'", "", $request->address) . "', '" . env('APP_KEY') . "'))");

        Patient::create($input);

        return redirect(route('patient.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $patient = Patient::find($id);

        return view('patient._user_view', compact('patient', $patient));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $patient = Patient::find($id);

        return view('patient._edit_user')->with('patient', $patient);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $patient          = Patient::find($id);
        $patient->name    = $request->name;
        $patient->email   = $request->email;
        $patient->phone   = $request->phone;
        $patient->address = $request->address;
        $patient->save();

        return redirect(route('patient.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $patient = Patient::findOrFail($id);
        $patient->delete();

        return redirect(route('patient.index'));
    }

    public function seedData(Faker $faker)
    {
        for ($i = 0; $i < 20; $i++)
        {
            Patient::create([
                'name'    => DB::raw("TO_BASE64(AES_ENCRYPT('" . str_replace("'", "", $faker->name()) . "', '" . env('APP_KEY') . "'))"),
                'email'   => DB::raw("TO_BASE64(AES_ENCRYPT('" . str_replace("'", "", $faker->email()) . "', '" . env('APP_KEY') . "'))"),
                'phone'   => DB::raw("TO_BASE64(AES_ENCRYPT('" . str_replace("'", "", $faker->phoneNumber()) . "', '" . env('APP_KEY') . "'))"),
                'address' => DB::raw("TO_BASE64(AES_ENCRYPT('" . str_replace("'", "", $faker->address()) . "', '" . env('APP_KEY') . "'))"),
            ]);
        }

        return redirect(route('patient.index'));
    }
}

resources/views/patient/_edit_user.blade.php
@extends('layout.master')
@section('title', 'user')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h3 class="m-0">User Form</h3>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active">Product v1</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body">
                    <form method="post" action="{{ route('patient.update',$patient->id) }} " enctype="multipart/form-data">
                        @csrf
                        @method('patch')
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" id="name" name="name" value="{{$patient->name ?? ''}}" >
                            @error('name')
                            <div class="text-danger"></div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="email" name="email" value="{{$patient->email ?? ''}}" >
                            @error('email')
                            <div class="text-danger"></div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="phone">Phone</label>
                            <input type="text" class="form-control" id="phone" name="phone" value="{{$patient->phone ?? ''}}">
                            @error('phone')
                            <div class="text-danger"></div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="address">Address</label>
                            <textarea class="form-control" id="address" name="address" >{{$patient->address ?? ''}}</textarea>
                            @error('address')
                            <div class="text-danger"></div>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-sm btn-primary">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/patient/_from.blade.php
@extends('layout.master')
@section('title', 'user')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h3 class="m-0">User Form</h3>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active">Product v1</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body">
                <form method="post" action="{{ route('patient.store') }} " enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" class="form-control" id="name" name="name" value="">
                        @error('name')
                        <div class="text-danger"></div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" class="form-control" id="email" name="email" value="">
                        @error('email')
                        <div class="text-danger"></div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="phone">Phone</label>
                        <input type="text" class="form-control" id="phone" name="phone" value="">
                        @error('phone')
                        <div class="text-danger"></div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="address">Address</label>
                        <textarea class="form-control" id="address" name="address"></textarea>
                        @error('address')
                        <div class="text-danger"></div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-sm btn-primary">Save</button>
                </form>
            </div>
        </div>
        </div>
    </section>

@endsection

resources/views/patient/_user_view.blade.php
@extends('layout.master')
@section('title', 'user')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h3 class="m-0">User</h3>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active"></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body">
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" id="name" name="name" value="{{$patient->name ?? ''}}" readonly>
                            @error('name')
                            <div class="text-danger"></div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="email" name="email" value="{{$patient->email ?? ''}}" readonly>
                            @error('email')
                            <div class="text-danger"></div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="phone">Phone</label>
                            <input type="text" class="form-control" id="phone" name="phone" value="{{$patient->phone ?? ''}}"readonly>
                            @error('phone')
                            <div class="text-danger"></div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="address">Address</label>
                            <textarea class="form-control" id="address" name="address" readonly>{{$patient->address ?? ''}}</textarea>
                            @error('address')
                            <div class="text-danger"></div>
                            @enderror
                        </div>
                        <a href="{{route('patient.index')}}" class="btn btn-sm btn-primary">Back</a>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/patient/index.blade.php
@extends('layout.master')
@section('title', 'Patient Management')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h3 class="m-0">Patient Management</h3>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active">Patients</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">

                            <div class="row">
                                <div class="col-md-6 mt-1">
                                    <form method="get" action="{{route('patient.index')}}" class="float-left w-50 mr-2" id="search-from">
                                        <div class="input-group ">
                                            <input type="text" class="form-control form-control-sm " id="search-text"
                                                   placeholder="Search by Name, Email, Phone, Address"
                                                   name="search" value="{{request()->query('search', '')}}">
                                            <div class="input-group-append">
                                                <button type="submit" id="search-btn" class="btn btn-sm btn-default search-btn-submit">
                                                    <i class="fa fa-search"></i>
                                                </button>
                                                <button type="reset" class="btn btn-sm btn-default search-reset">
                                                    <i class="fa fa-refresh" aria-hidden="true"></i>
                                                    Reset
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>

                                <div class="col-md-6 d-flex justify-content-sm-end mt-1">
                                    <a href="{{route('patient.seeder')}}" class="btn btn-sm btn-outline-success mr-2">
                                        <i class="fa fa-database" aria-hidden="true"></i>
                                        Seeder
                                    </a>
                                    <a href="{{route('patient.create')}}" class="btn btn-sm btn-outline-success">
                                        <i class="fa fa-plus"></i> New
                                    </a>
                                </div>
                            </div>
                        </div>

                        <div class="card-body table-responsive p-0">
                            <table class="table table-hover text-nowrap table-striped  table-bordered ">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Phone</th>
                                    <th>Address</th>
                                    <th class="text-center">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if(count($patients) > 0)
                                    @foreach($patients as $patient)
                                        <tr>
                                            <td>{{$patient->name}}</td>
                                            <td>{{$patient->email}}</td>
                                            <td>{{$patient->phone}}</td>
                                            <td><span class="tag tag-success">{{$patient->address}}</span></td>
                                            <td class="text-center">
                                                <a class="btn btn-primary btn-sm mr-2 "
                                                   href="{{route('patient.show',$patient->id)}}">
                                                    <i class="fas fa-folder"></i>
                                                    View
                                                </a>
                                                <a class="btn btn-info btn-sm mr-2"
                                                   href="{{route('patient.edit',$patient->id)}}">
                                                    <i class="fas fa-pencil-alt"></i>
                                                    Edit
                                                </a>
                                                <a class="btn btn-danger btn-sm"
                                                   href="" data-bs-toggle="modal"
                                                   data-bs-target="#exampleModal{{$patient->id}}">
                                                    <i class="fas fa-trash"></i>
                                                    Delete
                                                </a>
                                                <form action="{{route('patient.destroy',$patient->id)}}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <!-- Modal -->
                                                    <div class="modal fade" id="exampleModal{{$patient->id}}">
                                                        <div class="modal-dialog ">
                                                            <div class="modal-content">
                                                                <div class="modal-header bg-danger">
                                                                    <h5 class="modal-title" id="exampleModalLabel">Are
                                                                        you
                                                                        sure to delete this item ?</h5>
                                                                    <button type="button" class="close"
                                                                            data-bs-dismiss="modal"> ×
                                                                    </button>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="button"
                                                                            class="btn btn-sm btn-outline-secondary "
                                                                            data-bs-dismiss="modal">cancel
                                                                    </button>
                                                                    <button class="btn btn-sm btn-outline-danger ">
                                                                        Delete
                                                                    </button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                @else
                                    <tr>
                                        <td colspan="5">
                                            <p class="text-center text-danger">There is no data found, please seed it for testing.</p>
                                        </td>
                                    </tr>
                                @endif
                                </tbody>
                            </table>
                            <div class="d-flex justify-content-end mr-4 mt-3">
                                {{ $patients->links()}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('customJs')
    <script type="text/javascript">
        $(document).ready(function() {
            $('.search-reset').click(function () {
                $('#search-text').val('');
                $('.search-btn-submit').click();
            });
        });
    </script>
@endsection