routes/web.php
<?php

use App\Http\Controllers\PatientController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [UserController::class, 'index']);
Route::resources(['user' => UserController::class]);
Route::get('seed/data', [UserController::class, 'seedData'])->name('user.seeder');

Route::resources(['patient' => PatientController::class]);
Route::get('seed-data', [PatientController::class, 'seedData'])->name('patient.seeder');

resources/views/layout/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; 2014-2023 <a href="#">{{ env('APP_NAME') }}</a>.</strong>
    All rights reserved.
</footer>

resources/views/layout/header.blade.php
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@yield('title',env('app_name'))</title>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('adminlte/plugins/fontawesome-free/css/all.min.css')}}">
    <link rel="stylesheet" href="{{asset('adminlte/plugins/fontawesome-free/font-awesome-4.7.0/css/font-awesome.min.css')}}">


    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
{{--    sweat  alter--}}
{{--    <link rel="stylesheet" href="{{asset('adminlte/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css')}}">--}}

<!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
{{--<!-- DataTables -->--}}
{{--    <link rel="stylesheet" href="{{asset('adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">--}}
{{--    <link rel="stylesheet" href="{{asset('adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">--}}
{{--    <link rel="stylesheet" href="{{asset('adminlte/plugins/datatables-buttons/css/buttons.bootstrap4.min.css')}}">--}}
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('adminlte/dist/css/adminlte.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.1/dist/sweetalert2.min.css" rel="stylesheet">

    {{--toastr--}}
    <link rel="stylesheet" href="{{asset('adminlte/plugins/toastr/toastr.min.css')}}">

    <meta name="csrf-token" content="{{csrf_token()}}">
    <!-- Css files-->
    <link rel="stylesheet" type="text/css" href="{{asset('adminlte/plugins/simple-image-cropper/css/style.css')}}" />
    <link rel="stylesheet" type="text/css" href="{{asset('adminlte/plugins/simple-image-cropper/css/style-example.css')}}"    />
    <link rel="stylesheet" type="text/css" href="{{asset('adminlte/plugins/simple-image-cropper/css/jquery.Jcrop.min.css')}}" />
    <!-- Js files-->
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="{{asset('adminlte/plugins/simple-image-cropper/scripts/jquery.Jcrop.js')}}"></script>
    <script type="text/javascript" src="{{asset('adminlte/plugins/simple-image-cropper/scripts/jquery.SimpleCropper.js')}}"></script>
</head>

resources/views/layout/master.blade.php
<!DOCTYPE html>
<html lang="en">
@include('layout.header')
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
    @include('layout.navbar')
    @include('layout.sidebar')
    <div class="content-wrapper">
        @yield('content')
    </div>
    @include('layout.footer')
</div>
<div id="modal-placeholder"></div>
@include('layout.script')
@yield('costume_js')
</body>
</html>

resources/views/layout/navbar.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

</nav>
<!-- /.navbar -->

resources/views/layout/script.blade.php
<!-- jQuery -->
<script src="{{asset('adminlte/plugins/jquery/jquery.min.js')}}"></script>
<script src="{{asset('adminlte/plugins/jquery-ui/jquery-ui.js')}}"></script>
<!-- Bootstrap 4 -->
<script src="{{asset('adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('adminlte/dist/js/adminlte.js')}}"></script>
<!-- jquery-validation -->
<script src="{{asset('adminlte/plugins/jquery-validation/jquery.validate.js')}}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
@yield('customJs')

resources/views/layout/sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{asset('adminlte/dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2"
                     alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block text-capitalize">{{ env('APP_NAME') }}</a>
            </div>
        </div>


        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a href="{{route('user.index')}}" class="nav-link">
                        <i class="nav-icon fas fa-user-alt" aria-hidden="true"></i>
                        <p>Users</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('patient.index')}}" class="nav-link">
                        <i class="nav-icon fa fa-users fa-2x" aria-hidden="true"></i>
                        <p>Patients</p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>