routes/web.php
<?php

use App\Http\Controllers\PatientController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [UserController::class, 'index']);
Route::resources(['user' => UserController::class]);
Route::get('seed/data', [UserController::class, 'seedData'])->name('user.seeder');

Route::resources(['patient' => PatientController::class]);
Route::get('seed-data', [PatientController::class, 'seedData'])->name('patient.seeder');

app/Models/User.php
<?php

namespace App\Models;

use ESolution\DBEncryption\Traits\EncryptedAttribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    use HasFactory;
    use EncryptedAttribute;

    protected $fillable = ['name', 'email', 'phone', 'address'];

    protected $encryptable = ['name', 'email', 'phone', 'address'];

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Faker\Generator as Faker;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $search = \request('search', '');

        $users = User::where(function ($q) use ($search) {
            if ($search)
            {
                $q->whereEncrypted('name', 'LIKE', "%$search%");
                $q->orWhereEncrypted('email', 'LIKE', "%$search%");
                $q->orWhereEncrypted('phone', 'LIKE', "%$search%");
                $q->orWhereEncrypted('address', 'LIKE', "%$search%");
            }
        })->paginate();

        return view('user.index')->with('users', $users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user._from');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'    => 'required',
            'email'   => 'required|email|unique:users',
            'phone'   => 'required',
            'address' => 'required',
        ]);

        User::create($request->all());

        return redirect(route('user.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);

        return view('user._user_view', compact('user', $user));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);

        return view('user._edit_user')->with('user', $user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user          = User::find($id);
        $user->name    = $request->name;
        $user->email   = $request->email;
        $user->phone   = $request->phone;
        $user->address = $request->address;
        $user->save();

        return redirect(route('user.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();

        return redirect(route('user.index'));
    }

    public function seedData(Faker $faker)
    {
        for ($i = 0; $i < 20; $i++)
        {
            User::create([
                'name'    => $faker->name(),
                'email'   => $faker->email(),
                'phone'   => $faker->phoneNumber(),
                'address' => $faker->address()
            ]);
        }

        return redirect(route('user.index'));
    }
}

resources/views/user/_edit_user.blade.php
@extends('layout.master')
@section('title', 'user')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h3 class="m-0">User Form</h3>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active">Product v1</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body">
                    <form method="post" action="{{ route('user.update',$user->id) }} " enctype="multipart/form-data">
                        @csrf
                        @method('patch')
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" id="name" name="name" value="{{$user->name ?? ''}}" >
                            @error('name')
                            <div class="text-danger"></div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="email" name="email" value="{{$user->email ?? ''}}" >
                            @error('email')
                            <div class="text-danger"></div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="phone">Phone</label>
                            <input type="text" class="form-control" id="phone" name="phone" value="{{$user->phone ?? ''}}">
                            @error('phone')
                            <div class="text-danger"></div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="address">Address</label>
                            <textarea class="form-control" id="address" name="address" >{{$user->address ?? ''}}</textarea>
                            @error('address')
                            <div class="text-danger"></div>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-sm btn-primary">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/user/_from.blade.php
@extends('layout.master')
@section('title', 'user')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h3 class="m-0">User Form</h3>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active">Product v1</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body">
                <form method="post" action="{{ route('user.store') }} " enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" class="form-control" id="name" name="name" value="">
                        @error('name')
                        <div class="text-danger"></div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" class="form-control" id="email" name="email" value="">
                        @error('email')
                        <div class="text-danger"></div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="phone">Phone</label>
                        <input type="text" class="form-control" id="phone" name="phone" value="">
                        @error('phone')
                        <div class="text-danger"></div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="address">Address</label>
                        <textarea class="form-control" id="address" name="address"></textarea>
                        @error('address')
                        <div class="text-danger"></div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-sm btn-primary">Save</button>
                </form>
            </div>
        </div>
        </div>
    </section>

@endsection

resources/views/user/_user_view.blade.php
@extends('layout.master')
@section('title', 'user')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h3 class="m-0">User</h3>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active"></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body">
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" id="name" name="name" value="{{$user->name ?? ''}}" readonly>
                            @error('name')
                            <div class="text-danger"></div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="email" name="email" value="{{$user->email ?? ''}}" readonly>
                            @error('email')
                            <div class="text-danger"></div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="phone">Phone</label>
                            <input type="text" class="form-control" id="phone" name="phone" value="{{$user->phone ?? ''}}"readonly>
                            @error('phone')
                            <div class="text-danger"></div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="address">Address</label>
                            <textarea class="form-control" id="address" name="address" readonly>{{$user->address ?? ''}}</textarea>
                            @error('address')
                            <div class="text-danger"></div>
                            @enderror
                        </div>
                        <a href="{{route('user.index')}}" class="btn btn-sm btn-primary">Back</a>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/user/index.blade.php
@extends('layout.master')
@section('title', 'User Management')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h3 class="m-0">User Management</h3>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active">Users</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">

                            <div class="row">
                                <div class="col-md-6 mt-1">
                                    <form method="get" action="{{route('user.index')}}" class="float-left w-50 mr-2">
                                        <div class="input-group ">
                                            <input type="text" class="form-control form-control-sm" id="search-text"
                                                   placeholder="Search by Name, Email, Phone, Address"
                                                   name="search" value="{{request()->query('search', '')}}">
                                            <div class="input-group-append">
                                                <button type="submit" id="search-btn" class="btn btn-sm btn-default search-btn-submit">
                                                    <i class="fa fa-search"></i>
                                                </button>
                                                <button type="reset" class="btn btn-sm btn-default search-reset">
                                                    <i class="fa fa-refresh" aria-hidden="true"></i>
                                                    Reset
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>

                                <div class="col-md-6 d-flex justify-content-sm-end mt-1">
                                    <a href="{{route('user.seeder')}}" class="btn btn-sm btn-outline-success mr-2">
                                        <i class="fa fa-database" aria-hidden="true"></i>
                                        Seeder
                                    </a>
                                    <a href="{{route('user.create')}}" class="btn btn-sm btn-outline-success">
                                        <i class="fa fa-plus"></i> New
                                    </a>
                                </div>
                            </div>
                        </div>

                        <div class="card-body table-responsive p-0">
                            <table class="table table-hover text-nowrap table-striped  table-bordered ">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Phone</th>
                                    <th>Address</th>
                                    <th class="text-center">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if(count($users) > 0)
                                    @foreach($users as $user)
                                        <tr>
                                            <td>{{$user->name}}</td>
                                            <td>{{$user->email}}</td>
                                            <td>{{$user->phone}}</td>
                                            <td><span class="tag tag-success">{{$user->address}}</span></td>
                                            <td class="text-center">
                                                <a class="btn btn-primary btn-sm mr-2 "
                                                   href="{{route('user.show',$user->id)}}">
                                                    <i class="fas fa-folder"></i>
                                                    View
                                                </a>
                                                <a class="btn btn-info btn-sm mr-2"
                                                   href="{{route('user.edit',$user->id)}}">
                                                    <i class="fas fa-pencil-alt"></i>
                                                    Edit
                                                </a>
                                                <a class="btn btn-danger btn-sm"
                                                   href="" data-bs-toggle="modal"
                                                   data-bs-target="#exampleModal{{$user->id}}">
                                                    <i class="fas fa-trash"></i>
                                                    Delete
                                                </a>
                                                <form action="{{route('user.destroy',$user->id)}}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <!-- Modal -->
                                                    <div class="modal fade" id="exampleModal{{$user->id}}">
                                                        <div class="modal-dialog ">
                                                            <div class="modal-content">
                                                                <div class="modal-header bg-danger">
                                                                    <h5 class="modal-title" id="exampleModalLabel">Are
                                                                        you
                                                                        sure to delete this item ?</h5>
                                                                    <button type="button" class="close"
                                                                            data-bs-dismiss="modal"> ×
                                                                    </button>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="button"
                                                                            class="btn btn-sm btn-outline-secondary "
                                                                            data-bs-dismiss="modal">cancel
                                                                    </button>
                                                                    <button class="btn btn-sm btn-outline-danger ">
                                                                        Delete
                                                                    </button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                @else
                                    <tr>
                                        <td colspan="5">
                                            <p class="text-center text-danger">There is no data found, please seed it for testing.</p>
                                        </td>
                                    </tr>
                                @endif
                                </tbody>
                            </table>
                            <div class="d-flex justify-content-end mr-4 mt-3">
                                {{ $users->links() ?? '' }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('customJs')
    <script type="text/javascript">
        $(document).ready(function() {
            $('.search-reset').click(function () {
                $('#search-text').val('');
                $('.search-btn-submit').click();
            });
        });
    </script>
@endsection